# .air.toml
[build]
  cmd = "go build -o ./tmp/app ./cmd/main.go"
  bin = "./tmp/app"
  full_bin = "APP_ENV=dev ./tmp/app"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor"]
