services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: cvuser
      POSTGRES_PASSWORD: cvpass
      POSTGRES_DB: cvdb
    ports:
      - "5432:5432"

  analyzer-app:
    build: ../jobanalyzer
    working_dir: /app
    depends_on:
      - kafka
    command: python main.py
    env_file:
      - .env
    volumes:
      - ../jobanalyzer:/app
