services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"   # 👈 for dev convenience

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: cvuser
      POSTGRES_PASSWORD: cvpass
      POSTGRES_DB: cvdb
    ports:
      - "5432:5432"

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9095:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - ~/kui/config.yml:/etc/kafkaui/dynamic_config.yaml
      # analyzer-app:
      #   build: ../jobanalyzer
      #   working_dir: /app
      #   depends_on:
      #     - kafka
      #   command: python main.py
      #   env_file:
      #   - .env
      #volumes:
      #- ../jobanalyzer:/app
  # kafdrop:
  #   image: obsidiandynamics/kafdrop
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     KAFKA_BROKERCONNECT: "kafka:9092"     # 👈 this matches kafka service name
  #     JVM_OPTS: "-Xms32M -Xmx64M"
  #   depends_on:
  #     - kafka
