// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: applications.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveApplication = `-- name: ApproveApplication :execrows
UPDATE applications
SET status = 'approved', updated_at = now()
WHERE id = $1 AND user_id = $2 AND status = 'awaiting_approval'
`

type ApproveApplicationParams struct {
	ID     int64
	UserID int64
}

// Approve moves an awaiting_approval application to approved so the worker
// submits it. Owner-scoped; only valid from awaiting_approval.
func (q *Queries) ApproveApplication(ctx context.Context, arg ApproveApplicationParams) (int64, error) {
	result, err := q.db.Exec(ctx, approveApplication, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countAwaitingApproval = `-- name: CountAwaitingApproval :one
SELECT COUNT(*)
FROM applications
WHERE user_id = $1 AND status = 'awaiting_approval'
`

func (q *Queries) CountAwaitingApproval(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAwaitingApproval, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const discardApplication = `-- name: DiscardApplication :execrows
UPDATE applications
SET status = 'discarded', updated_at = now()
WHERE id = $1 AND user_id = $2
  AND status IN ('queued','filling','awaiting_approval','failed')
`

type DiscardApplicationParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DiscardApplication(ctx context.Context, arg DiscardApplicationParams) (int64, error) {
	result, err := q.db.Exec(ctx, discardApplication, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getApplication = `-- name: GetApplication :one
SELECT id, user_id, cv_id, job_id, status, filled_inputs, error, submitted_at, created_at, updated_at, submission_screenshot, result_screenshot, tailored_cv_path FROM applications WHERE id = $1
`

func (q *Queries) GetApplication(ctx context.Context, id int64) (Application, error) {
	row := q.db.QueryRow(ctx, getApplication, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CvID,
		&i.JobID,
		&i.Status,
		&i.FilledInputs,
		&i.Error,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmissionScreenshot,
		&i.ResultScreenshot,
		&i.TailoredCvPath,
	)
	return i, err
}

const getResultScreenshot = `-- name: GetResultScreenshot :one
SELECT result_screenshot FROM applications WHERE id = $1 AND user_id = $2
`

type GetResultScreenshotParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetResultScreenshot(ctx context.Context, arg GetResultScreenshotParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getResultScreenshot, arg.ID, arg.UserID)
	var result_screenshot []byte
	err := row.Scan(&result_screenshot)
	return result_screenshot, err
}

const getSubmissionScreenshot = `-- name: GetSubmissionScreenshot :one
SELECT submission_screenshot FROM applications WHERE id = $1 AND user_id = $2
`

type GetSubmissionScreenshotParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetSubmissionScreenshot(ctx context.Context, arg GetSubmissionScreenshotParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSubmissionScreenshot, arg.ID, arg.UserID)
	var submission_screenshot []byte
	err := row.Scan(&submission_screenshot)
	return submission_screenshot, err
}

const listApplications = `-- name: ListApplications :many
SELECT
  a.id, a.status, a.filled_inputs, a.error, a.submitted_at, a.created_at, a.updated_at,
  a.cv_id, a.job_id,
  (a.submission_screenshot IS NOT NULL) AS has_submission_screenshot,
  (a.result_screenshot IS NOT NULL) AS has_result_screenshot,
  j.title, j.company, j.location, j.url, j.source
FROM applications AS a
JOIN jobs AS j ON j.id = a.job_id
WHERE a.user_id = $1
ORDER BY a.updated_at DESC
LIMIT $2 OFFSET $3
`

type ListApplicationsParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

type ListApplicationsRow struct {
	ID                      int64
	Status                  string
	FilledInputs            []byte
	Error                   pgtype.Text
	SubmittedAt             pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	CvID                    pgtype.Int8
	JobID                   int64
	HasSubmissionScreenshot interface{}
	HasResultScreenshot     interface{}
	Title                   pgtype.Text
	Company                 pgtype.Text
	Location                pgtype.Text
	Url                     pgtype.Text
	Source                  string
}

func (q *Queries) ListApplications(ctx context.Context, arg ListApplicationsParams) ([]ListApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listApplications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsRow
	for rows.Next() {
		var i ListApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.FilledInputs,
			&i.Error,
			&i.SubmittedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CvID,
			&i.JobID,
			&i.HasSubmissionScreenshot,
			&i.HasResultScreenshot,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Url,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueApplication = `-- name: QueueApplication :exec
INSERT INTO applications (user_id, cv_id, job_id, status, tailored_cv_path)
VALUES ($1, $2, $3, 'queued',
        (SELECT e.tailored_cv_path FROM job_evaluations AS e
         WHERE e.cv_id = $2 AND e.job_id = $3))
ON CONFLICT (user_id, job_id) DO NOTHING
`

type QueueApplicationParams struct {
	UserID int64
	CvID   pgtype.Int8
	JobID  int64
}

func (q *Queries) QueueApplication(ctx context.Context, arg QueueApplicationParams) error {
	_, err := q.db.Exec(ctx, queueApplication, arg.UserID, arg.CvID, arg.JobID)
	return err
}

const updateApplicationInputs = `-- name: UpdateApplicationInputs :execrows
UPDATE applications
SET filled_inputs = $3, updated_at = now()
WHERE id = $1 AND user_id = $2 AND status = 'awaiting_approval'
`

type UpdateApplicationInputsParams struct {
	ID           int64
	UserID       int64
	FilledInputs []byte
}

// UpdateApplicationInputs saves the user's edited field values. Owner-scoped and
// only while awaiting_approval, so an in-flight or submitted application can't be
// rewritten. The submit phase replays exactly these values.
func (q *Queries) UpdateApplicationInputs(ctx context.Context, arg UpdateApplicationInputsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateApplicationInputs, arg.ID, arg.UserID, arg.FilledInputs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
