// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cv_analysis.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createCVAnalysis = `-- name: CreateCVAnalysis :one
INSERT INTO cv_analyses (file_name, original_name, parsed_text, status, user_id)
VALUES ($1, $2, $3, $4, $5) RETURNING id, original_name, file_name, parsed_text, structured_json, status, user_id, created_at, updated_at, errors
`

type CreateCVAnalysisParams struct {
	FileName     string
	OriginalName string
	ParsedText   pgtype.Text
	Status       string
	UserID       pgtype.Int8
}

func (q *Queries) CreateCVAnalysis(ctx context.Context, arg CreateCVAnalysisParams) (CvAnalysis, error) {
	row := q.db.QueryRow(ctx, createCVAnalysis,
		arg.FileName,
		arg.OriginalName,
		arg.ParsedText,
		arg.Status,
		arg.UserID,
	)
	var i CvAnalysis
	err := row.Scan(
		&i.ID,
		&i.OriginalName,
		&i.FileName,
		&i.ParsedText,
		&i.StructuredJson,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Errors,
	)
	return i, err
}

const getAllCVAnalysis = `-- name: GetAllCVAnalysis :many
SELECT id, original_name, file_name, parsed_text, structured_json, status, user_id, created_at, updated_at, errors
FROM cv_analyses
WHERE ($3::text[] IS NULL OR status = ANY($3))
AND user_id = $4
ORDER BY created_at DESC LIMIT $1
OFFSET $2
`

type GetAllCVAnalysisParams struct {
	Limit   int32
	Offset  int32
	Column3 []string
	UserID  pgtype.Int8
}

func (q *Queries) GetAllCVAnalysis(ctx context.Context, arg GetAllCVAnalysisParams) ([]CvAnalysis, error) {
	rows, err := q.db.Query(ctx, getAllCVAnalysis,
		arg.Limit,
		arg.Offset,
		arg.Column3,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CvAnalysis
	for rows.Next() {
		var i CvAnalysis
		if err := rows.Scan(
			&i.ID,
			&i.OriginalName,
			&i.FileName,
			&i.ParsedText,
			&i.StructuredJson,
			&i.Status,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Errors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCVAnalysis = `-- name: GetCVAnalysis :one
SELECT id, original_name, file_name, parsed_text, structured_json, status, user_id, created_at, updated_at, errors
FROM cv_analyses
WHERE id = $1
`

func (q *Queries) GetCVAnalysis(ctx context.Context, id int64) (CvAnalysis, error) {
	row := q.db.QueryRow(ctx, getCVAnalysis, id)
	var i CvAnalysis
	err := row.Scan(
		&i.ID,
		&i.OriginalName,
		&i.FileName,
		&i.ParsedText,
		&i.StructuredJson,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Errors,
	)
	return i, err
}

const getCVEmbedding = `-- name: GetCVEmbedding :one
SELECT cv_id, canonical_text, skills_text, responsibilities_text, canonical_text_embeddings, skills_text_embeddings, responsibilities_text_embeddings, created_at, updated_at
FROM cv_embeddings
WHERE cv_id = $1
`

func (q *Queries) GetCVEmbedding(ctx context.Context, cvID int64) (CvEmbedding, error) {
	row := q.db.QueryRow(ctx, getCVEmbedding, cvID)
	var i CvEmbedding
	err := row.Scan(
		&i.CvID,
		&i.CanonicalText,
		&i.SkillsText,
		&i.ResponsibilitiesText,
		&i.CanonicalTextEmbeddings,
		&i.SkillsTextEmbeddings,
		&i.ResponsibilitiesTextEmbeddings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDistinctSkills = `-- name: GetDistinctSkills :many
SELECT DISTINCT tech::text AS technology
FROM cv_analyses,
LATERAL jsonb_array_elements(structured_json->'technologies') AS tech
WHERE structured_json IS NOT NULL
`

func (q *Queries) GetDistinctSkills(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getDistinctSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var technology string
		if err := rows.Scan(&technology); err != nil {
			return nil, err
		}
		items = append(items, technology)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctSkillsForCV = `-- name: GetDistinctSkillsForCV :many
SELECT DISTINCT tech::text AS technology
FROM cv_analyses,
LATERAL jsonb_array_elements(structured_json->'technologies') AS tech
WHERE structured_json IS NOT NULL
AND id = $1
`

func (q *Queries) GetDistinctSkillsForCV(ctx context.Context, id int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getDistinctSkillsForCV, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var technology string
		if err := rows.Scan(&technology); err != nil {
			return nil, err
		}
		items = append(items, technology)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCVEmbedding = `-- name: InsertCVEmbedding :exec
INSERT INTO cv_embeddings (cv_id, canonical_text, skills_text, responsibilities_text, canonical_text_embeddings, skills_text_embeddings, responsibilities_text_embeddings)
VALUES ($1, $2, $3, $4, $5, $6, $7) ON CONFLICT (cv_id) DO
UPDATE SET
    canonical_text = EXCLUDED.canonical_text,
    skills_text = EXCLUDED.skills_text,
    responsibilities_text = EXCLUDED.responsibilities_text,
    canonical_text_embeddings = EXCLUDED.canonical_text_embeddings,
    skills_text_embeddings = EXCLUDED.skills_text_embeddings,
    responsibilities_text_embeddings = EXCLUDED.responsibilities_text_embeddings,
    updated_at = now()
`

type InsertCVEmbeddingParams struct {
	CvID                           int64
	CanonicalText                  pgtype.Text
	SkillsText                     pgtype.Text
	ResponsibilitiesText           pgtype.Text
	CanonicalTextEmbeddings        pgvector.Vector
	SkillsTextEmbeddings           pgvector.Vector
	ResponsibilitiesTextEmbeddings pgvector.Vector
}

func (q *Queries) InsertCVEmbedding(ctx context.Context, arg InsertCVEmbeddingParams) error {
	_, err := q.db.Exec(ctx, insertCVEmbedding,
		arg.CvID,
		arg.CanonicalText,
		arg.SkillsText,
		arg.ResponsibilitiesText,
		arg.CanonicalTextEmbeddings,
		arg.SkillsTextEmbeddings,
		arg.ResponsibilitiesTextEmbeddings,
	)
	return err
}

const updateCVErrors = `-- name: UpdateCVErrors :exec
UPDATE cv_analyses
SET errors = $2,
    status = 'error'
WHERE id = $1
`

type UpdateCVErrorsParams struct {
	ID     int64
	Errors []byte
}

func (q *Queries) UpdateCVErrors(ctx context.Context, arg UpdateCVErrorsParams) error {
	_, err := q.db.Exec(ctx, updateCVErrors, arg.ID, arg.Errors)
	return err
}

const updateCVParsedText = `-- name: UpdateCVParsedText :exec
UPDATE cv_analyses
SET parsed_text = $2,
    status      = 'parsed',
    errors      = NULL
WHERE id = $1
`

type UpdateCVParsedTextParams struct {
	ID         int64
	ParsedText pgtype.Text
}

func (q *Queries) UpdateCVParsedText(ctx context.Context, arg UpdateCVParsedTextParams) error {
	_, err := q.db.Exec(ctx, updateCVParsedText, arg.ID, arg.ParsedText)
	return err
}

const updateCVStatus = `-- name: UpdateCVStatus :exec
UPDATE cv_analyses
SET status = $2
WHERE id = $1
`

type UpdateCVStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) UpdateCVStatus(ctx context.Context, arg UpdateCVStatusParams) error {
	_, err := q.db.Exec(ctx, updateCVStatus, arg.ID, arg.Status)
	return err
}

const updateCVStructuredJSON = `-- name: UpdateCVStructuredJSON :exec
UPDATE cv_analyses
SET structured_json = $2,
    status          = 'analyzed',
    errors          = NULL
WHERE id = $1
`

type UpdateCVStructuredJSONParams struct {
	ID             int64
	StructuredJson []byte
}

func (q *Queries) UpdateCVStructuredJSON(ctx context.Context, arg UpdateCVStructuredJSONParams) error {
	_, err := q.db.Exec(ctx, updateCVStructuredJSON, arg.ID, arg.StructuredJson)
	return err
}

const updateCVStructuredJSONManual = `-- name: UpdateCVStructuredJSONManual :exec
UPDATE cv_analyses
SET structured_json = $2,
    updated_at      = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $3
`

type UpdateCVStructuredJSONManualParams struct {
	ID             int64
	StructuredJson []byte
	UserID         pgtype.Int8
}

// Manual user edit of the parsed CV — updates only the JSON, leaving status
// untouched (unlike UpdateCVStructuredJSON, which flips status to 'analyzed').
func (q *Queries) UpdateCVStructuredJSONManual(ctx context.Context, arg UpdateCVStructuredJSONManualParams) error {
	_, err := q.db.Exec(ctx, updateCVStructuredJSONManual, arg.ID, arg.StructuredJson, arg.UserID)
	return err
}
