// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cv_analysis.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createCVAnalysis = `-- name: CreateCVAnalysis :one
INSERT INTO cv_analyses (file_name, original_name, parsed_text, status)
VALUES ($1, $2, $3, $4) RETURNING id, original_name, file_name, parsed_text, structured_json, status, created_at, updated_at, errors
`

type CreateCVAnalysisParams struct {
	FileName     string
	OriginalName string
	ParsedText   pgtype.Text
	Status       string
}

func (q *Queries) CreateCVAnalysis(ctx context.Context, arg CreateCVAnalysisParams) (CvAnalysis, error) {
	row := q.db.QueryRow(ctx, createCVAnalysis,
		arg.FileName,
		arg.OriginalName,
		arg.ParsedText,
		arg.Status,
	)
	var i CvAnalysis
	err := row.Scan(
		&i.ID,
		&i.OriginalName,
		&i.FileName,
		&i.ParsedText,
		&i.StructuredJson,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Errors,
	)
	return i, err
}

const createJobEmbedding = `-- name: CreateJobEmbedding :exec
INSERT INTO jobs_embeddings (job_id, embedding)
VALUES ($1, $2)  -- $2 is a vector literal/array cast
ON CONFLICT (job_id)
DO UPDATE SET
  embedding  = EXCLUDED.embedding,
  updated_at = now()
`

type CreateJobEmbeddingParams struct {
	JobID     int64
	Embedding pgvector.Vector
}

func (q *Queries) CreateJobEmbedding(ctx context.Context, arg CreateJobEmbeddingParams) error {
	_, err := q.db.Exec(ctx, createJobEmbedding, arg.JobID, arg.Embedding)
	return err
}

const getAllCVAnalysis = `-- name: GetAllCVAnalysis :many
SELECT id, original_name, file_name, parsed_text, structured_json, status, created_at, updated_at, errors
FROM cv_analyses
WHERE ($3::text[] IS NULL OR status = ANY($3))
ORDER BY created_at DESC LIMIT $1
OFFSET $2
`

type GetAllCVAnalysisParams struct {
	Limit   int32
	Offset  int32
	Column3 []string
}

func (q *Queries) GetAllCVAnalysis(ctx context.Context, arg GetAllCVAnalysisParams) ([]CvAnalysis, error) {
	rows, err := q.db.Query(ctx, getAllCVAnalysis, arg.Limit, arg.Offset, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CvAnalysis
	for rows.Next() {
		var i CvAnalysis
		if err := rows.Scan(
			&i.ID,
			&i.OriginalName,
			&i.FileName,
			&i.ParsedText,
			&i.StructuredJson,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Errors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCVAnalysis = `-- name: GetCVAnalysis :one
SELECT id, original_name, file_name, parsed_text, structured_json, status, created_at, updated_at, errors
FROM cv_analyses
WHERE id = $1
`

func (q *Queries) GetCVAnalysis(ctx context.Context, id int64) (CvAnalysis, error) {
	row := q.db.QueryRow(ctx, getCVAnalysis, id)
	var i CvAnalysis
	err := row.Scan(
		&i.ID,
		&i.OriginalName,
		&i.FileName,
		&i.ParsedText,
		&i.StructuredJson,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Errors,
	)
	return i, err
}

const getCVEmbedding = `-- name: GetCVEmbedding :one
SELECT embedding
FROM cv_analyses_embeddings
WHERE cv_id = $1
`

func (q *Queries) GetCVEmbedding(ctx context.Context, cvID int64) (pgvector.Vector, error) {
	row := q.db.QueryRow(ctx, getCVEmbedding, cvID)
	var embedding pgvector.Vector
	err := row.Scan(&embedding)
	return embedding, err
}

const getDistinctSkills = `-- name: GetDistinctSkills :many
SELECT DISTINCT tech::text AS technology
FROM cv_analyses,
LATERAL jsonb_array_elements(structured_json->'technologies') AS tech
WHERE structured_json IS NOT NULL
`

func (q *Queries) GetDistinctSkills(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getDistinctSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var technology string
		if err := rows.Scan(&technology); err != nil {
			return nil, err
		}
		items = append(items, technology)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctSkillsForCV = `-- name: GetDistinctSkillsForCV :many
SELECT DISTINCT tech::text AS technology
FROM cv_analyses,
LATERAL jsonb_array_elements(structured_json->'technologies') AS tech
WHERE structured_json IS NOT NULL
AND id = $1
`

func (q *Queries) GetDistinctSkillsForCV(ctx context.Context, id int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getDistinctSkillsForCV, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var technology string
		if err := rows.Scan(&technology); err != nil {
			return nil, err
		}
		items = append(items, technology)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCVEmbedding = `-- name: InsertCVEmbedding :exec
INSERT INTO cv_analyses_embeddings (cv_id, embedding)
VALUES ($1, $2) ON CONFLICT (cv_id) DO
UPDATE SET embedding = EXCLUDED.embedding
`

type InsertCVEmbeddingParams struct {
	CvID      int64
	Embedding pgvector.Vector
}

func (q *Queries) InsertCVEmbedding(ctx context.Context, arg InsertCVEmbeddingParams) error {
	_, err := q.db.Exec(ctx, insertCVEmbedding, arg.CvID, arg.Embedding)
	return err
}

const updateCVErrors = `-- name: UpdateCVErrors :exec
UPDATE cv_analyses
SET errors = $2
WHERE id = $1
`

type UpdateCVErrorsParams struct {
	ID     int64
	Errors []byte
}

func (q *Queries) UpdateCVErrors(ctx context.Context, arg UpdateCVErrorsParams) error {
	_, err := q.db.Exec(ctx, updateCVErrors, arg.ID, arg.Errors)
	return err
}

const updateCVParsedText = `-- name: UpdateCVParsedText :exec
UPDATE cv_analyses
SET parsed_text = $2,
    status      = 'parsed'
WHERE id = $1
`

type UpdateCVParsedTextParams struct {
	ID         int64
	ParsedText pgtype.Text
}

func (q *Queries) UpdateCVParsedText(ctx context.Context, arg UpdateCVParsedTextParams) error {
	_, err := q.db.Exec(ctx, updateCVParsedText, arg.ID, arg.ParsedText)
	return err
}

const updateCVStatus = `-- name: UpdateCVStatus :exec
UPDATE cv_analyses
SET status = $2
WHERE id = $1
`

type UpdateCVStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) UpdateCVStatus(ctx context.Context, arg UpdateCVStatusParams) error {
	_, err := q.db.Exec(ctx, updateCVStatus, arg.ID, arg.Status)
	return err
}

const updateCVStructuredJSON = `-- name: UpdateCVStructuredJSON :exec
UPDATE cv_analyses
SET structured_json = $2,
    status          = 'analyzed'
WHERE id = $1
`

type UpdateCVStructuredJSONParams struct {
	ID             int64
	StructuredJson []byte
}

func (q *Queries) UpdateCVStructuredJSON(ctx context.Context, arg UpdateCVStructuredJSONParams) error {
	_, err := q.db.Exec(ctx, updateCVStructuredJSON, arg.ID, arg.StructuredJson)
	return err
}
