// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: evaluations.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getJobEvaluation = `-- name: GetJobEvaluation :one
SELECT cv_id, job_id, score, final_decision, machine_summary, report_path,
       tailored_cv_path, evaluator, model, status, requested_at, error, evaluated_at
FROM job_evaluations
WHERE cv_id = $1 AND job_id = $2
`

type GetJobEvaluationParams struct {
	CvID  int64
	JobID int32
}

type GetJobEvaluationRow struct {
	CvID           int64
	JobID          int32
	Score          pgtype.Numeric
	FinalDecision  pgtype.Text
	MachineSummary []byte
	ReportPath     pgtype.Text
	TailoredCvPath pgtype.Text
	Evaluator      string
	Model          pgtype.Text
	Status         string
	RequestedAt    pgtype.Timestamptz
	Error          pgtype.Text
	EvaluatedAt    pgtype.Timestamptz
}

func (q *Queries) GetJobEvaluation(ctx context.Context, arg GetJobEvaluationParams) (GetJobEvaluationRow, error) {
	row := q.db.QueryRow(ctx, getJobEvaluation, arg.CvID, arg.JobID)
	var i GetJobEvaluationRow
	err := row.Scan(
		&i.CvID,
		&i.JobID,
		&i.Score,
		&i.FinalDecision,
		&i.MachineSummary,
		&i.ReportPath,
		&i.TailoredCvPath,
		&i.Evaluator,
		&i.Model,
		&i.Status,
		&i.RequestedAt,
		&i.Error,
		&i.EvaluatedAt,
	)
	return i, err
}

const requestJobEvaluation = `-- name: RequestJobEvaluation :execrows

INSERT INTO job_evaluations (cv_id, job_id, status, requested_at)
VALUES ($1, $2, 'requested', now())
ON CONFLICT (cv_id, job_id) DO UPDATE
SET status = 'requested', requested_at = now(), error = NULL
WHERE job_evaluations.status IN ('done', 'failed')
`

type RequestJobEvaluationParams struct {
	CvID  int64
	JobID int32
}

// Deep-evaluation queue: career-ops A-G evaluations requested from the UI and
// processed by the jobbridge watch worker (claude -p). Statuses:
// requested -> running -> done | failed.
func (q *Queries) RequestJobEvaluation(ctx context.Context, arg RequestJobEvaluationParams) (int64, error) {
	result, err := q.db.Exec(ctx, requestJobEvaluation, arg.CvID, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
