// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: jobs.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :exec
INSERT INTO jobs (source_id, source, title, company, logo, url, description, tags, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (source, source_id) DO NOTHING
`

type CreateJobParams struct {
	SourceID    pgtype.Text
	Source      string
	Title       pgtype.Text
	Company     pgtype.Text
	Logo        pgtype.Text
	Url         pgtype.Text
	Description pgtype.Text
	Tags        []string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.db.Exec(ctx, createJob,
		arg.SourceID,
		arg.Source,
		arg.Title,
		arg.Company,
		arg.Logo,
		arg.Url,
		arg.Description,
		arg.Tags,
		arg.CreatedAt,
	)
	return err
}
