// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: learned_answers.sql

package repository

import (
	"context"
)

const listLearnedAnswers = `-- name: ListLearnedAnswers :many
SELECT label, value FROM learned_answers WHERE user_id = $1
`

type ListLearnedAnswersRow struct {
	Label string
	Value string
}

func (q *Queries) ListLearnedAnswers(ctx context.Context, userID int64) ([]ListLearnedAnswersRow, error) {
	rows, err := q.db.Query(ctx, listLearnedAnswers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLearnedAnswersRow
	for rows.Next() {
		var i ListLearnedAnswersRow
		if err := rows.Scan(&i.Label, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLearnedAnswer = `-- name: UpsertLearnedAnswer :exec
INSERT INTO learned_answers (user_id, label, value, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (user_id, label) DO UPDATE
  SET value = EXCLUDED.value, updated_at = now()
`

type UpsertLearnedAnswerParams struct {
	UserID int64
	Label  string
	Value  string
}

func (q *Queries) UpsertLearnedAnswer(ctx context.Context, arg UpsertLearnedAnswerParams) error {
	_, err := q.db.Exec(ctx, upsertLearnedAnswer, arg.UserID, arg.Label, arg.Value)
	return err
}
