// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type CvAnalysis struct {
	ID             int64
	OriginalName   string
	FileName       string
	ParsedText     pgtype.Text
	StructuredJson []byte
	Status         string
	UserID         pgtype.Int8
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	Errors         []byte
}

type CvEmbedding struct {
	CvID                           int64
	CanonicalText                  pgtype.Text
	SkillsText                     pgtype.Text
	ResponsibilitiesText           pgtype.Text
	CanonicalTextEmbeddings        pgvector.Vector
	SkillsTextEmbeddings           pgvector.Vector
	ResponsibilitiesTextEmbeddings pgvector.Vector
	CreatedAt                      pgtype.Timestamp
	UpdatedAt                      pgtype.Timestamp
}

type CvJobMatch struct {
	CvID                int64
	JobID               int64
	Percentage          pgtype.Numeric
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	CanonicalPct        pgtype.Numeric
	SkillsPct           pgtype.Numeric
	ResponsibilitiesPct pgtype.Numeric
	DomainMultiplier    pgtype.Numeric
	RerankScore         pgtype.Numeric
	RerankDetails       []byte
	RerankedAt          pgtype.Timestamptz
}

type Job struct {
	ID                   int32
	SourceID             pgtype.Text
	Source               string
	Title                pgtype.Text
	Company              pgtype.Text
	Logo                 pgtype.Text
	Location             pgtype.Text
	Url                  pgtype.Text
	Tags                 []string
	Description          pgtype.Text
	PublishAt            pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	EmbeddingRequestedAt pgtype.Timestamptz
}

type JobFetchTask struct {
	ID        int32
	TaskID    string
	Platform  string
	Skills    []string
	Location  pgtype.Text
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type JobsEmbedding struct {
	ID                             int64
	JobID                          int64
	CanonicalText                  pgtype.Text
	SkillsText                     pgtype.Text
	ResponsibilitiesText           pgtype.Text
	CanonicalTextEmbeddings        pgvector.Vector
	SkillsTextEmbeddings           pgvector.Vector
	ResponsibilitiesTextEmbeddings pgvector.Vector
	CreatedAt                      pgtype.Timestamptz
	UpdatedAt                      pgtype.Timestamptz
}

type User struct {
	ID        int64
	Username  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
