// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CvAnalysis struct {
	ID             int64
	OriginalName   string
	FileName       string
	ParsedText     pgtype.Text
	StructuredJson []byte
	Status         string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}
