// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type CvAnalysesEmbedding struct {
	CvID      int64
	Embedding pgvector.Vector
	CreatedAt pgtype.Timestamp
}

type CvAnalysis struct {
	ID             int64
	OriginalName   string
	FileName       string
	ParsedText     pgtype.Text
	StructuredJson []byte
	Status         string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type Job struct {
	ID          int32
	SourceID    pgtype.Text
	Source      string
	Title       pgtype.Text
	Company     pgtype.Text
	Logo        pgtype.Text
	Location    pgtype.Text
	Url         pgtype.Text
	Tags        []string
	Description pgtype.Text
	PublishAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}
