// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package repository

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (email, username, password)
VALUES ($1, $2, $3)
`

type CreateUserParams struct {
	Email    string
	Username string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.Email, arg.Username, arg.Password)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, username, email, password, created_at, updated_at, preferred_company_sizes, preferred_industries, preferred_stages
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllUsers(ctx context.Context, arg GetAllUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PreferredCompanySizes,
			&i.PreferredIndustries,
			&i.PreferredStages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPreferencesByCvId = `-- name: GetPreferencesByCvId :one
SELECT u.preferred_company_sizes, u.preferred_industries, u.preferred_stages
FROM cv_analyses c
JOIN users u ON u.id = c.user_id
WHERE c.id = $1
`

type GetPreferencesByCvIdRow struct {
	PreferredCompanySizes []string
	PreferredIndustries   []string
	PreferredStages       []string
}

// Company-type preferences for the owner of a CV — used by the CV-driven
// crawl dispatch to scope scrapes without a separate lookup round-trip.
func (q *Queries) GetPreferencesByCvId(ctx context.Context, id int64) (GetPreferencesByCvIdRow, error) {
	row := q.db.QueryRow(ctx, getPreferencesByCvId, id)
	var i GetPreferencesByCvIdRow
	err := row.Scan(&i.PreferredCompanySizes, &i.PreferredIndustries, &i.PreferredStages)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password, created_at, updated_at, preferred_company_sizes, preferred_industries, preferred_stages
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreferredCompanySizes,
		&i.PreferredIndustries,
		&i.PreferredStages,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, email, password, created_at, updated_at, preferred_company_sizes, preferred_industries, preferred_stages
FROM users
WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreferredCompanySizes,
		&i.PreferredIndustries,
		&i.PreferredStages,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password, created_at, updated_at, preferred_company_sizes, preferred_industries, preferred_stages
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreferredCompanySizes,
		&i.PreferredIndustries,
		&i.PreferredStages,
	)
	return i, err
}

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT preferred_company_sizes, preferred_industries, preferred_stages
FROM users
WHERE id = $1
`

type GetUserPreferencesRow struct {
	PreferredCompanySizes []string
	PreferredIndustries   []string
	PreferredStages       []string
}

func (q *Queries) GetUserPreferences(ctx context.Context, id int64) (GetUserPreferencesRow, error) {
	row := q.db.QueryRow(ctx, getUserPreferences, id)
	var i GetUserPreferencesRow
	err := row.Scan(&i.PreferredCompanySizes, &i.PreferredIndustries, &i.PreferredStages)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password = $2
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID       int64
	Password string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.Password)
	return err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :exec
UPDATE users
SET preferred_company_sizes = $2,
    preferred_industries    = $3,
    preferred_stages        = $4,
    updated_at = now()
WHERE id = $1
`

type UpdateUserPreferencesParams struct {
	ID                    int64
	PreferredCompanySizes []string
	PreferredIndustries   []string
	PreferredStages       []string
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) error {
	_, err := q.db.Exec(ctx, updateUserPreferences,
		arg.ID,
		arg.PreferredCompanySizes,
		arg.PreferredIndustries,
		arg.PreferredStages,
	)
	return err
}
