// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package repository

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (email, username, password)
VALUES ($1, $2, $3)
`

type CreateUserParams struct {
	Email    string
	Username string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.Email, arg.Username, arg.Password)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, username, email, password, created_at, updated_at, preferred_company_sizes
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllUsers(ctx context.Context, arg GetAllUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PreferredCompanySizes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPreferredSizesByCvId = `-- name: GetPreferredSizesByCvId :one
SELECT u.preferred_company_sizes
FROM cv_analyses c
JOIN users u ON u.id = c.user_id
WHERE c.id = $1
`

// Company-size preference for the owner of a CV — used by the CV-driven
// crawl dispatch to scope scrapes without a separate lookup round-trip.
func (q *Queries) GetPreferredSizesByCvId(ctx context.Context, id int64) ([]string, error) {
	row := q.db.QueryRow(ctx, getPreferredSizesByCvId, id)
	var preferred_company_sizes []string
	err := row.Scan(&preferred_company_sizes)
	return preferred_company_sizes, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password, created_at, updated_at, preferred_company_sizes
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreferredCompanySizes,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, email, password, created_at, updated_at, preferred_company_sizes
FROM users
WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreferredCompanySizes,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password, created_at, updated_at, preferred_company_sizes
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreferredCompanySizes,
	)
	return i, err
}

const getUserPreferredSizes = `-- name: GetUserPreferredSizes :one
SELECT preferred_company_sizes
FROM users
WHERE id = $1
`

func (q *Queries) GetUserPreferredSizes(ctx context.Context, id int64) ([]string, error) {
	row := q.db.QueryRow(ctx, getUserPreferredSizes, id)
	var preferred_company_sizes []string
	err := row.Scan(&preferred_company_sizes)
	return preferred_company_sizes, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password = $2
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID       int64
	Password string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.Password)
	return err
}

const updateUserPreferredSizes = `-- name: UpdateUserPreferredSizes :exec
UPDATE users
SET preferred_company_sizes = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateUserPreferredSizesParams struct {
	ID                    int64
	PreferredCompanySizes []string
}

func (q *Queries) UpdateUserPreferredSizes(ctx context.Context, arg UpdateUserPreferredSizesParams) error {
	_, err := q.db.Exec(ctx, updateUserPreferredSizes, arg.ID, arg.PreferredCompanySizes)
	return err
}
